package com.payment.payrowapp.utils

object Constants {
    const val SELECTED_TYPE: String = "SELECTED TYPE"
    const val MY_PREFERENCES: String = "MyPreferences"
    const val PAYROW_ID: String = "PayRowId"
    const val LOGIN_TYPE: String = "LoginType"
    const val LOGIN_TOKEN: String = "LoginToken"
    const val _ID: String = "ID"
    const val MERCHANT_ID: String = "MerchantId"
    const val USER_ID: String = "UserId"
    const val ROLE: String = "Role"
    const val STORE_ID: String = "StoreId"
    const val COMPLAINT_TYPE: String = "ComplaintType"
    const val USER_TYPE: String = "UserType"
    const val INVOICE_NUMBER: String = "InvoiceNumber"
    const val SELECTED_ITEMS_SIZE: String = "SelectedItemsSize"
    const val SELECTED_ITEMS: String = "SelectedItems"
    const val TRANSACTION_TYPE: String = "TransactionType"
    const val CASH: String = "Cash"
    const val CARD: String = "Card"
    const val TOTAL_AMOUNT: String = "TotalAmount"
    const val TOTAL_TAX: String = "TotalTax"
    const val ADDRESS: String = "Address"
    const val NAME_OF_THE_BUSINESS: String = "NameOfTheBusiness"
    const val DATE: String = "Date"
    const val FROM_DATE: String = "FromDate"
    const val TO_DATE: String = "ToDate"


    const val IS_LOGIN = "IS LOGIN"
    const val FROM = "FROM"
    const val TO = "TO"

    const val TERMINAL_ID = "TID"
    const val MERCHANT_MOBILE_NUMBER = "Mobile Number"
    const val EMAIL_ID = "Email ID"
    const val DISTRIBUTOR_ID = "Distributor ID"
    const val VISA_NUMBER = "Visa Number"
    const val FIRST_NAME = "First Name"
    const val LAST_NAME = "Last Name"
    const val BUSINESS_TYPE = "Business Type"
    const val BO_BOX = "BO Box"
    const val COUNTRY = "Country"
    const val ADDRESS_DETAILS = "Address Details"
    const val AMOUNT = "Amount"
    const val GENERATE_QR = "generateQR"

    const val SESSIONS_TIMEOUT_SEC = "600"
    const val EDIRHAM_CARD = "EDIRHAM_CARD"
    const val NON_EDIRHAM_CARD = "NON_EDIRHAM_CARD"
    const val CONFIG_FILES = "Config Files"
    const val PROFILE_READER = "ProfileReader.json"
    const val AdditionalInfo = "AdditionalInfo.json"
    const val CA_PUBLIC_KEYS = "CAPublicKeys.json"
    const val CERTIFICATE_REVOCATION_LIST = "CertificateRevocationList.json"
    const val DEFAULT_TERMINAL_DATA = "DefaultTerminalData.json"
    const val EXCEPTION_FILE = "ExceptionFile.json"
    const val MANIFEST = "manifest.json"
    const val PROFILE_DATA = "ProfileData.json"
    const val PROFILE_READER_ACTIVATE = "ProfileReaderActivate.json"
    const val PROFILE_READER_INITIALISE = "ProfileReaderInitialise.json"
    const val REFERENCE_TAGS = "ReferenceTags.json"
    const val TLV_TERMINAL = "tlvTerminal.json"
    const val V3_DATA_DICTIONARY = "v3DataDictionary.json"
    const val AES_KEY = "aesKey"
    const val IV = "iv"
    const val SELECTED_BOOL = "selected bool"
    const val CONTACTLESS_CONFIGURATION = "ContactLessConfiguration"
    const val VAT_PER = 5
}